/*
 * Audit Trail
 *
 * This is an Audit Trail service.

 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	model "mingo/audit/model"
	"testing"
)

type AuditTrailMock struct {
	mock.Mock
}

var mock AuditTrailMock

func (m *AuditTrailMock) AddEvent(ev model.Event) error {
	return m.Called(ev)
}

func (m *AuditTrailMock) GetEvents(query model.EventQuery) ([]model.Event, error) {
	return m.Called(query)
}

func TestGetEvents(t *testing.T) {
	restSvc := RestSvcImpl{&mock}
	restSvc.FindByType(writer, request)
}
