/*
 * Audit Trail
 *
 * This is an Audit Trail service.

 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import "testing"

func TestGetEvents(t *testing.T) {
}
